### ISSUE TITLE
input of function compute_spin_loss

### ISSUE THREAD

**Issue by THBUer-yw** [thomasgauthier/LLM-self-play#1]
In the line 87 of the .py file, why **opponent_logits_syn** is passed into the compute_spin_loss twice? Should it be the missing opponent_logits_gt that is not defined?

**Comment by thomasgauthier** [comment]
You're absolutely right, the `opponent_logits_gt` term was missing. The implementation in this repo was quickly put together and I didn't get to test it as I'm waiting on compute.

Fixed in ce23eb5
